### ISSUE TITLE
보드선택

### ISSUE THREAD

**Issue by lightreal** [KimGunSoo/sosohaniot#1]
## 보드 선택 확정

레퍼런스가 가장 많은 라즈베리파이로 결정
- 아두이노
- 라즈베리파이2 (결정)
- 갈릴레오

고려사항
1. 보드에 대한 자료가 많은지? (강좌, Q&A, etc)
2. HW 스펙? 등등이 부족하지 않은지? (드론을 만들기에 부족하지 않은지)

**Comment by kjunu** [comment]
형들 무슨 스터디 하는거에요? 저도 껴주셈 ㅋㅋㅋㅋ

**Comment by lightreal** [comment]
@kjunu IoT로 뭔가 해볼라고 ㅋㅋ

**Comment by kjunu** [comment]
아... 라즈베리파이 하나 업글되었군요. 이전에 사둔 거 쓸모없어지는 건가... 망이네요.

**Comment by kjunu** [comment]
http://prezi.com/
도식화하거나 이런덴 별 쓸모없었지만, 정말 발표를 위한 PT 자료툴이 필요할 때 쓸만하던데요 ㅎㅎㅎ

**Comment by lightreal** [comment]
@kjunu ㅋㅋㅋ 기존라즈베리파이는 성능에서만 차이나지 않을까?ㅋㅋ

**Comment by lightreal** [comment]
prezi는 큰 그림부터 세세한 부분으로 쪼개서 top - down 방식이나 순차적인 단계를 설명하기에 편함.
그러나 한글입력에 약간 버그가 있는듯(in chrome).
프레지 폴더에 Viewer 추가가 가능하나 뷰어가 업로드도 가능한지는 모르겠음.

**Comment by kjunu** [comment]
저는 라즈베리 파이 추천이요.
장점은 
1. os 다양한 점 arch, rasibian 스펠 맞던가;; , ubuntu, (2 는 windows 10까지 된다니... bsd 도 올려둔 사람 있고...)
2. 기존에 쌓여있는 자료들이 많음, 인지도 높음
을 들 수 있네요.

**Comment by lightreal** [comment]
거침없이배우는 라즈베리파이 라는 책도 있으니 스타팅할때 도움이 될 것 같긴해

**Comment by KimGunSoo** [comment]
라즈베리파이가 레퍼런스가 제일 많은것 같네

**Comment by lightreal** [comment]
그럼 오늘내에 구매하자~ 준우는 라즈1 있으니 구매안해도 되지?

**Comment by kjunu** [comment]
저는 일단 라즈1로 해보다가 뭔가 2랑 너무 차이가 난다 하면 2도 구입할깨요
