### ISSUE TITLE
라즈베리파이에 OS 올리기

### ISSUE THREAD

**Issue by KimGunSoo** [KimGunSoo/sosohaniot#10]
sd 카드 구매가 먼저 진행되어야 한다.

**Comment by lightreal** [comment]
- https://www.raspberrypi.org/downloads/
- NOOBS.zip을 다운로드 받아 압축을 풀어 sdcard에 넣는다
- sdcard를 라즈베리파이에 꼽고 부팅 후, 라즈베리안 인스톨한다.
- password, internalisation option(language) 같은 설정 후 finish를 눌러 부팅한다.
- 다음을 참조
  - [NOOBS로 라즈베리안 설치](http://voguebloom.blog.me/220037774604)

**Comment by KimGunSoo** [comment]
OS설치 및 ssh 환경구축할때 USB 키보드가 필요하다.
