### ISSUE TITLE
라즈베리파이로 모터제어가 가능한가??

### ISSUE THREAD

**Issue by lightreal** [KimGunSoo/sosohaniot#11]
- 라즈베리파이에 모터 직결하시면 안되고, 모터 드라이브나 대용량 트렌지스터/FET 사용해야 한다고 함
  - 잘못하면 과부하로 핀 망가짐
- 사례
  - [라즈베리파이로 자동차 만들기](http://lsj30224.blog.me/220273297594)
  - 자바로 코딩을 진행하였고, 이 경우에도 라즈베리파이에서 직접 모터제어가 안된다고 하여 모터드라이브를 통해 모터를 제어함
  - 추가 조사가 필요함

**Comment by lightreal** [comment]
- [라즈베리파이 DC모터 제어(자바)](http://blog.naver.com/dragon01254/220256173075)

**Comment by lightreal** [comment]
- [라즈베리파이 서보모터 제어(python)](http://blog.naver.com/roboholic84/220312905549)
- [회로도](http://blog.naver.com/roboholic84/220311651781)보면 알겠지만 모터드라이브를 사용하지 않은듯 함.
  - AA건전지를 따로 연결해서 사용함

**Comment by KimGunSoo** [comment]
위에 자동차 만들기 포스팅을 보니깐, 우드락이랑 음료수 뚜껑으로 외장을 구성했넹 ㅋㅋ

**Comment by KimGunSoo** [comment]
모터 드라이브를 사용하지 않은 회로도를 보고,
몇가지 조사해 봐야할 것들.

Q1> T-cobbler plus 라는게 gpio 확장 board 인가?

Q2> 그 gpio 확장 board를 사용하면, 여러개의 모터를 돌릴수 있나?

Q3> 흰색 board는 뭘까?
  브레드보드 : 납땜을 하지 않아도 연결하고 싶은 전자 부품의 다리를 브레드보드에 꽂아 쉽게 회로를 만들수 있게 해줌 ([브레드 보드 사용법](http://blog.naver.com/PostView.nhn?blogId=roboholic84&logNo=220304938273&parentCategoryNo=24&categoryNo=&viewDate=&isShowPopularPosts=true&from=search))

**Comment by lightreal** [comment]
A1> 코블러가 확장보드라고 되어있긴 한데 핀 숫자는 똑같은걸로 봐서 그냥 브레드보드에 쉽게 연결하기 위한 도구로 보임

**Comment by lightreal** [comment]
- [라즈베리파이로 RC카 만들기](http://www.icbanq.com/pbloger/board_View.aspx?number=362)
- 기존모터드라이브 사용하지 않았고, AA건전지 네개와 브레드패드, quadruple half-h driver 인 ‘SN754410NE’를 이용해 모터드라이브를 직접 제작

**Comment by KimGunSoo** [comment]
헉, 위에 링크가 우리한테 딱 알맞은거 같은데? ([라즈베리파이로 RC카 만들기](http://www.icbanq.com/pbloger/board_View.aspx?number=362))

**유력후보1**. 브레드 패드에 건전지와 모터를 연결하는 방식을 이용하자. SN754410NE 필요. 
  또다른 참고자료와 회로도 : [SN754410NE 칩을 이용한 바이폴라 스테핑 모터](http://blog.danggun.net/2067)

**Comment by KimGunSoo** [comment]
#### 스텝모터의 유니폴라와 바이폴라
- 유니폴라 vs. 바이폴라
  - 유니폴라 : 전자와 정공 중 한쪽만이 캐리어 되는 것
  - 바이폴라 : 동작의 바탕이 되는 캐리어가 두 종류가 있음. 전자나 정공이 캐리어가 되는 것
- 스텝모터의 유니폴라
  - 구동 방식 : 모터의 권선에 흐르는 전류가 항상 한쪽 방향으로만 흐르는 구동방식
  - 고속으로 구동시 토크가 높아 탈조될 위험이 적어, 고속회전에 용이
  - 비교적 구동 회로가 간단함
  - 모터 코일에 저장된 에너리를 회생하지 않으므로 효율이 떨어짐
  - 저속에서 구동시 토크가 바이폴라에 비해 적음
- 스텝모터의 바이폴라
  - 구동 방식 : 모터의 권선에 흐르는 전류의 방향이 바뀌는 구동방식
  - 저속 구동시 토크가 높음
  - 코일에 저장된 전류가 회생되어 효율이 높음
  - 고속 구동시 토크가 급격하게 저하되어 탈조가 발생할 우려가 있음
  - 구동 회로의 구성이 복잡함

ref : [스텝모터의 유니폴라와 바이폴라](http://soswing.tistory.com/41)

**Comment by lightreal** [comment]
- 브레드패드 사용법을 좀 알아야 할 것 같기도 해 ㅎㅎ 아무데나 쑤셨다가는... 똥망될것같기도 해서 ㅋ

**Comment by KimGunSoo** [comment]
#### 스텝모터 vs. 서보모터

##### 장점
- 스텝모터의 장점
  - 안정성 : 마찰과 관성부하의 넓은 범위를 수용가능. 오작동 및 혼선 시 멈춤.  기계적 과부하는 스텝모터에 손상을 입히지 않음
  - 가격 : 비교적 비싸지 않음
  - 표준화 : 표준 NEMA 프레임 사이즈 & 성능
  - 전원, 작동 : 사용과 설치가 쉬움
  - 탁월할 저속토크
  - 반복성 : 같은 위치로 정확하게 돌아감 (Open loop system)
  - 오랜 수명 : 10,000 시간의 작동 수명
- 서보모터의 장점
  - 높은 출력 : 서보모터의 크기와 무게에 따른 파워
  - 높은 효율 : 경부하에서 90%의 효율성
  - 높은 토크 : 빠르게 가속 가능
  - 짧은 시간에 2~3번의 연속 출력이 가능
  - 작동시 울림과 진동이 없음
  - 고속에서 소음 없음

##### 단점
- 스텝모터의 단점
  - 낮은 효율
  - 토크가 빠르게 떨어짐
  - 울림현상이 생기는 경우가 있기 때문에, 부드러운 작동을 위해 마이크로 스테핑이 필요함
  - 고속에서 심한 열을 받음 (히트싱크, 쿨러 필요)
  - 낮은 출력전원
- 서보모터의 단점
  - 비싼 비용
  - 피드백 회로를 안정화 하기위해 튜닝필요
  - 보호회로 필요
  - 복합함 (엔코더 필요 : 서보모터의 정확도와 회전도를 결정)
  - 수명이 짧음 : 약 2,000 시간
  - 최대 회전력의 제한 ???
  - 모터 쿨링이 약함 ???

ref : [스텝모터와 서보모터 차이점](http://blog.naver.com/motor2662/220004996734)

**Comment by KimGunSoo** [comment]
#### 스텝모터 vs. 서보모터 둘중 하나를 선택 해야합니다.

암묵적으로 이미 **서보모터**를 생각하고 있는거 맞죠?
@lightreal 이 올린 링크자료도 서보모터를 구동하는 것이니, 참고할만한 자료는 있습니다.

댓글에 추가적인 이견이 없다면, **서보모터로 결정**하는것으로 하죠.

**Comment by KimGunSoo** [comment]
#### DC모터와 서보모터

서보모터는 DC모터의 한 종류입니다.
- DC모터
  - Direct Current의 약자이며 축이 연속적으로 회전하는 형태의 모터로서 전원이 끊어지는 경우에만 정지합니다.
- 서보모터
  -  DC모터의 한 종류로 DC 모터에 귀환회로를 추가하여 정확한 위치제어가 가능하도록 구성된 모터입니다. 정밀제어가 가능하고 스텝모터에 비해 빠른 장점이 있습니다.

ref: [DC모터, 서보모터, 적외선 센서](http://blog.naver.com/jscom_/220183590350)

**Comment by lightreal** [comment]
궁금한게 있는데 서보모터는 방향성만 관여하고 고속회전력은 없는걸로 보이는데...
서보모터로만 결정한다는게 맞는지를 모르겠네~

**Comment by KimGunSoo** [comment]
이 이슈아이템 목적은 이룬것 같습니다. 고로 내일 쯤 close 합니다.
목적 : 라즈베리파이로 모터제어가 가능한가? 
결론 : 가능하다

다음 작업은 모터관련 디바이스들을 선택하고 구매해야 합니다.
- 모터 (DC모터, 서보모터, 스텝모터, 드론모터)
  - DC 모터 3개
- 모터 드라이브 chip : SN754410NE
- 브레드 보드
- 배터리
  - 건전지 몇볼트 : 위 [링크](http://www.icbanq.com/pbloger/board_View.aspx?number=362)에서 보면 1.5V 짜리 4개를 직렬연결했으므로, 6V 인데,,
  - 건전지 소켓
- 연결 선들(모터 두개기준)
  - female-male : 최소 7개 이상
  - male-male : 최소 14개 이상
  - 40개 1세트 f-m 1세트, m-m 2세트, f-f 1세트 
- 기타 등등
- [모터, 모터드라이브](http://www.ds-parts.co.kr)
- [건전지소켓, 브레드보드, 점퍼케이블](http://powernet1.godo.co.kr/shop)

@lightreal @kjunu : 내일부터는 어떤 디바이스를 선택할지 알아보고 주문들어 갑시다. ㅎㅎ

**Comment by KimGunSoo** [comment]
#### 정리 제안

알고 있으면 좀 좋을것 같은 주제들에 대해서는 여기에 정리를 합시다.

예를들어, 회로 구성관련 지식들(모터 드라이브 chip 스펙, 브레드보드 스펙)은 링크만 남기지 말고,
여기에 요약하여 타이핑하는게 어떨까요?

**Comment by KimGunSoo** [comment]
라즈베리파이(+ Quadcopter)를 이용해서 드론을 만들려고 하는 사람이 있긴하네. ㅎㅎ

[Quadcopter & Raspberry Pi & QtCreator: 유투브](https://www.youtube.com/watch?v=xJnofzew29k)
[라즈베리파이 드론](http://www.rasplay.org/?p=4492)
[QUADCOPTER: github](https://github.com/vjaunet/QUADCOPTER)

**Comment by KimGunSoo** [comment]
#### QUADCOPTER

위에 링크한 github 내용을 간략하게 정리합니다.
[QUADCOPTER: github](https://github.com/vjaunet/QUADCOPTER)

Android App에서 드론을 제어하는 구조입니다.
- 사용한 하드웨어 구성품들은
  - 가속 자이로 센서 : MPU6050
  - wifi 동글
  - 모터 : 4 brushless motors (TURNIGY 2204-14T 19g Outrunner)
  - ESC : 4 Electronic Speed Controllers (Turnigy Multistar 10 Amp)
  - 배터리 : 1 LiPo 3s 3700 mAh battery
  - 프레임 : QuadCopter frame
- 사용한 소프트웨어 모듈은 : ServoBlaster
  - ESC signal generator
  - PWM signal을 만들어준다. :  servo는 PWN signal이 필요하다. 
  - [Servo control](http://cihatkeser.com/servo-control-with-raspberry-pi-in-5-minutes-or-less/)
  
  > As you know servos need PWM signals to drive them, which requires a rather precise timing that is hard to achieve in user space of a non-realtime operating system.
  > Thanks to the ServoBlaster driver by Richard Hirst we don't even have to think about those pesky timing stuff.
  > What ServoBlaster does in its most basic form is to provide you with the ability to produce PWM signals from any of Raspberry Pi's GPIO pins.

**Comment by kjunu** [comment]
잘 만들려고 하면 위에 적힌 것 처럼 자이로센서....
그리고 GPS 가 필요할 수도...

**Comment by KimGunSoo** [comment]
#### Brushless Direct Current 모터 (BLDC 모터)

모르는게 너무 많다..
Q1> BLDC 모터는 일반 DC 모터랑 차이가 있는건가?
Q2> ESC가 필요한 모터와 필요없는 모터가 구분되어 있나?
Q3> ESC 없어도 모터드라이브(SN754410NE)랑 일반 DC모터만 있어도 되는거 같은데, ESC가 없으면 단점이 뭐지? 속도제어가 안되나?

[BLDC motor 설계 지원기술](http://blog.naver.com/PostView.nhn?blogId=polytechzone&logNo=140055134942)

**Comment by ecorium** [comment]
코멘트 작성을 위한 테스트 입력

**Comment by lightreal** [comment]
- 주문한 물품 오늘(4/30)내로 모두 도착할 예정

**Comment by KimGunSoo** [comment]
우선 현재 정리된 내용과 부품으로 진행해 보고, 한계점이나 개선사항 issue 들은 다른 issue로 등록하겠습니다.
