### ISSUE TITLE
OS 를 어떻게 올릴 것인가?

### ISSUE THREAD

**Issue by kjunu** [KimGunSoo/sosohaniot#12]
이번 주 내로 기본적인 환경은 잡을 것 같은데요.

하나 결정해야할 것이 있습니다.
1. OS 를 소스코드 받아서 컴파일 해서 이미지 만들어 올린다.
2. 배포되고 있는 이미지를 받아서 올린다.

앞으로 직접 OS 레이어에 뭔가를 변경할 일이 있을 것이라고 예상되면 1 을 아니면 2 를 선택하면 될 것 같은데요. 의견 부탁 드려요.

**Comment by KimGunSoo** [comment]
중요한 문제인것 같네.
몇가지 생각나는데로 적어보자면,
- OS 레이어에 변경할 만한 일들은 어떤것들이 있을까?

> vendor driver나 HW제어 interface 등은 아마 user 레벨에서 추가할수 있을것 같고.
> 우리가 예상 가능한것들은 뭐가 있을까?
- 라즈베리안의 커널만 바꿔서 이미지를 구성하기가 쉬운가?

> 라즈베리안 이미지가 커널+플랫폼 형식으로 구분되어 있다면 변경이 쉬운 구조일텐데.

커널 이미지만 교체하는 방식이 쉽고 + OS 레이어에 변경해야할 것들이 딱히 없다면,
배포되고 있는 이미지를 그대로 사용하다가, OS 레이어에 변경할 일이 생기면, 그때 커널 이미지만 교체하는 방법을 추천합니다.

**Comment by KimGunSoo** [comment]
참고 : [커널 크로스 컴파일 방법](http://webnautes.tistory.com/547)

**Comment by lightreal** [comment]
rasberry_img/os/Raspbian/boot.tar.xz 에 kernel.img와 kernel7.img가 있음
나중에 참고할 수 있을 듯

**Comment by KimGunSoo** [comment]
우선 배포되는 이미지를 사용하고, 추후 필요시 kernel만 교체하는 방법을 찾아 봅시다.

**Comment by kjunu** [comment]
라즈비안 구워서 주신 건 모니터에 연결해서 ssh 켜야하는 것 같더라구요. 저는 모니터가 없는 관계로 그냥 자동으로 ssh 켜지는 arch linux 로 세팅해서 작업합니다. 늘 켜놓고 있어서 거의 고정 아이피 ㅎㅎㅎ 저는 어디서나 접속할 수 있어요 ㅋ ssh app 도 설치함 ㅋ
