### ISSUE TITLE
Restful API 에 대한 고민

### ISSUE THREAD

**Issue by kjunu** [KimGunSoo/sosohaniot#13]
python framework

https://www.djangoproject.com/

우선 올려둡니다.

**Comment by kjunu** [comment]
http://pueue.com/setting-up-project-with-python-34-and-django-17-on-raspberry-pi/ 

라즈베리파이에 django 설치하기

**Comment by KimGunSoo** [comment]
django 설치하는데 발생한 오류들
- 데이터베이스 만들기 오류
  
  > $ mysql -u pi -p
  >   Enter password:
  >  ERROR 1045 (28000): Access denied for user 'pi'@'localhost' (using password: YES) 
  - [mysql user관리](http://blog.naver.com/marundubu/120166942800)
- python django에 mySQL 설정 오류
  
  > django 프로젝트에서 settings.py를 찾을수가 없다.
  > python의 버젼 차이일까?
  - 내부에 같은 이름의 django project 폴더가 더 만들어 지는데, 거기에 settings.py가 있음

**Comment by KimGunSoo** [comment]
#### django 사용법 간단 정리
- 설치
  - 기본적으로 '[rasp에 python/django 셋업](http://pueue.com/setting-up-project-with-python-34-and-django-17-on-raspberry-pi/)' 사이트를 참고하였습니다.
  - 필요없는 내용 : mysql 설치, python version up
  - 필수 설치 해야할 것들 : pip(python 라이브러리 관리), python용 django
- django프로젝트 생성
  - django-admin.py startproject "프로젝트 이름"
  - 추후, 해당 project 폴더를 github에 올려둘 생각입니다. (network 환경 차이로 인한 부작용이 있을수도...)
- django 서버 실행
  - 프로젝트 폴더로 이동
  - ./manage.py runserver 0.0.0.0:8000
  - 외부의 웹브라우져로 http://"라즈베리파이 IP":8000 접속됨을 확인
  - ![django_server_connection](https://cloud.githubusercontent.com/assets/4301661/7528527/4c056630-f564-11e4-8d3c-312d03c75e16.jpg)

**Comment by kjunu** [comment]
python 이랑 django version 알려주세요~ 다같이 같은 버전으로 정해서 가죠 ㅎㅎ

**Comment by kjunu** [comment]
저는 1 이라 그런지 sudo python get-pip.py 가 꽤 시간을 잡아먹었네요 한... 5분정도?

**Comment by KimGunSoo** [comment]
python 이랑 django version 공유합니다.
- python version : 2.7.3
  - 확인 방법 : python --version
- django version : 1.8.1
  - 확인 방법 : pip show django

**Comment by KimGunSoo** [comment]
#### django 사용법 간단 정리 2

먼저, 위의 django 사용법 간단정리를 참고하여 설치 및 django 프로젝트를 생성을 완료하세요.
데이터베이스 사용법과, django app을 만들어서 간단한 url 핸들링하는 법을 정리합니다.
(데이터베이스 설정이 꼭 필요한지는 아직 모르겠음)
- 데이터베이스 사용
  - django 프로젝트 폴더로 이동 후
  - ./manage.py migrate
  - ./manage.py createsuperuser
  - 서버 구동 : ./manage.py runserver 0.0.0.0:8000
  - 외부의 웹브라우져로 http://"라즈베리파이 IP":8000/admin 접속하면 super user로 login됨을 확인
  - ![django_admin](https://cloud.githubusercontent.com/assets/4301661/7601452/310a61d2-f951-11e4-8afe-948ecf94a070.jpg)
- django App 만들기
  - django 프로젝트 폴더로 이동 후
  - ./manage.py startapp 앱이름
  - 앱이름으로 된 directory가 생성 되며, 내부에 python script 파일이 생성됨.(역할이 있겠지요?ㅎㅎ)
  - ![django_app_tree](https://cloud.githubusercontent.com/assets/4301661/7601525/25d2fab2-f952-11e4-93f2-d734b3f73fee.jpg)
- django 프로젝트에 django App 추가하기
  - django 프로젝트 폴더로 이동 후
  - <프로젝트이름>/settings.py 파일의 INSTALLED_APPS 수정 ("rasp_if"는 내가 설정한 앱이름)
  - ![django_app_setting](https://cloud.githubusercontent.com/assets/4301661/7601559/d126ad82-f952-11e4-84be-fa307157f847.jpg)
- django App에 URL handler 추가하기
  - <앱이름>/views.py에 handler 추가 (꼭 views.py일 필요는 없을것 같다)
  - 다음 키워드로 handler를 정의 : def 핸들러명(request):
  - 예제. rasp_cmd, index 핸들러 정의
  - ![django_app_handler1](https://cloud.githubusercontent.com/assets/4301661/7601615/cfdf7d9a-f953-11e4-9f5a-979d1d93e885.jpg)
  - 특정 URL이 불리면, 해당 handler를 호출해 주는 코드 작성
  - <프로젝트이름>/urls.py
  - 예제. rasp_cmd, index 핸들러 호출
  - ![django_app_handler2](https://cloud.githubusercontent.com/assets/4301661/7601659/7c0e6ca2-f954-11e4-8ef5-a5b109c6d285.jpg)
  - ![django_app_handler3](https://cloud.githubusercontent.com/assets/4301661/7601690/dd5dd7a4-f954-11e4-962b-e98892aaabfb.jpg)
  - ![django_app_handler4](https://cloud.githubusercontent.com/assets/4301661/7601693/e39359e6-f954-11e4-9859-2955b7c73a4f.jpg)

**Comment by lightreal** [comment]
- browser에서 모터 컨트롤하기
  - ![django_motor_control](https://cloud.githubusercontent.com/assets/4945725/7739493/ba3b9c54-ff9c-11e4-98f1-44a1864c589e.gif)
  - 해당 django project 코드는 git에 올려두었습니다.

**Comment by KimGunSoo** [comment]
#### django server 스크립트

간단히 django server를 실행 시키는 스크립트를 git에 올려 두었습니다.

실행 방법은 README 파일에 적어 두었습니다.

```
pi@(none) ~/my_project/sosohaniot $ ./01_run_django_server.sh
```

**Comment by KimGunSoo** [comment]
#### django command 리스트

django command를 추가 하였습니다.

command 설명은 README 파일에 적어두었습니다.
- command
  - rasp_cmd_init : GPIO 초기화
  - rasp_cmd_deinit : GPIO 클린업
  - rasp_cmd_getstate : GPIO 초기화 여부
  - rasp_cmd_go : 0.1초간 앞으로 감
  - rasp_cmd_back :  0.1초간 뒤로 감

**Comment by KimGunSoo** [comment]
Restful API에 대한 간단한 구동은 완료하였으므로, 이 이슈는 닫습니다.
client App or web 환경에서의 django 사용방법은 새로운 이슈(#20)에서 관리합니다.
