### ISSUE TITLE
Wifi 모듈에 대한 고민

### ISSUE THREAD

**Issue by kjunu** [KimGunSoo/sosohaniot#14]
모듈 구입

모듈 컨트롤

**Comment by KimGunSoo** [comment]
wifi 모듈 구입 완료 : iptime N 100 mini

**Comment by KimGunSoo** [comment]
[라즈베리파이 wifi 동글 설정](http://jonghyunkim816.blogspot.kr/2013/10/wifi-usb.html)

/etc/network/interfaces 파일을 직접 수정하는 방식이다.

```
auto lo

iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan0
auto wlan0

iface wlan0 inet dhcp
        wpa-ssid "공유기이름"
        wpa-psk "비밀번호"
```
- 특이사항
  - ~~@lightreal 환경에서는 위의 방식으로 하면, eth와 wlan이 동시에 안되는 문제가 있다.~~ -> NAT 재설정하여 해결

**Comment by KimGunSoo** [comment]
#### wifi 모듈을 설정해보니 겪는것
1. 기존 eth0 역시 사용해야 한다.
   - Desktop에서는 wifi가 안되므로 ssh 접속하려면 기존 eth0를 사용해야함
   - 아니면, Desktop에도 wifi 동글을 끼우던지...
   - 암튼, 불편함이 전혀 줄지 않았음.
2. mobile에서 브라우져로 django cmd를 날릴수 있게 되었다.
   - mobile Application을 개발할 타이밍이 왔나???
3. ~~eth와 wlan이 동시에 안되는 상황도 발생 한다.~~ -> NAT 재설정하여 해결
   - ~~해결책 찾는데 많은 시간이 소요될 듯하다.~~

**Comment by kjunu** [comment]
1번은 무선공유기가 없어서 문제가 생기는거죠?

**Comment by KimGunSoo** [comment]
@kjunu 응 맞아 ㅋㅋ 데스크탑에 무선공유기나 무서랜카드가 있으면 됨

**Comment by KimGunSoo** [comment]
wifi USB 동글을 이용하여, 무선으로 커맨드를 보낼수 있게 되었으므로 이슈를 닫습니다.
추후, 다른 프로토콜(wifi Direct, BT, ...)을 선택 할 경우에는 새로운 이슈를 생성합니다.
