### ISSUE TITLE
python으로 하드웨어 제어하기

### ISSUE THREAD

**Issue by KimGunSoo** [KimGunSoo/sosohaniot#15]
- 개요
  - 라즈베리파이 안에서 구동시킬 프로그램을 python으로 작성하기로 결정하였습니다.
  - python을 이용하여 하드웨어(ex. 모터)를 제어하는 방법을 알아봅시다.

**Comment by KimGunSoo** [comment]
[원격으로 RC카 제어](http://www.icbanq.com/pbloger/board_View.aspx?number=362)을 참고하여 python으로 모터를 구동시켜 보자.

**Comment by kjunu** [comment]
https://github.com/kjunu/hello/tree/master/euler python 공부할 때 작성한 코드인데 참고 하세요ㅎㅎㅎ

구글링 하면 아주 좋은 자료가 많은데 그래도 혹시 도움이 될 까 하여 ㅎㅎ

**Comment by KimGunSoo** [comment]
### 모터 구동 성공

python으로 gpio를 제어하여 모터가 돌아가는 것을 확인 하였습니다.
- 회로도
  - ![rpi_sn7544110ne](https://cloud.githubusercontent.com/assets/4301661/7449364/a33db080-f26f-11e4-8524-f74dcbf15f96.jpg)
- 소스 코드 : python 코드는  github(sosohaniot/src/in_rasp/motor_control.py)에 올려두었습니다.
- 사용한 gpio
  - ground pin# 6
  - motor1 : GPIO14 / GPIO15 / GPIO18
  - motor2 : GPIO25 / GPIO08 / GPIO07

특이사항 : SN7544110NE 의 제약인지는 모르겠으나, 1개의 모터만 구동하고 싶을때도, chip의 양쪽 결선을 다 해주어야합니다.

**Comment by lightreal** [comment]
- GPIO가 HIGH인 상태에서 인터럽트(Ctrl + C)로 인해 종료를 하게 되면 HIGH인 상태가 계속 유지 됨.
  - 예외 상황 발생시에 cleanup 필요
- motor 속도 제어를 위해서는 PWM관리가 필요할 듯

**Comment by lightreal** [comment]
- 도움될만한 참조사이트
  - [RC카 라즈베리파이](https://www.youtube.com/watch?v=CYHOpkVeWq8)
  - [RC카 라즈베리파이 github](https://github.com/iobear/rpi-car)
  - [RC탱크 라즈베리파이](https://www.youtube.com/watch?v=9QbIDQHhmi8)
  - [RC탱크 라즈베리파이 github](https://github.com/FreddyKilo/Frank_the_Tank)
  - [web에서 gpio제어(webiopi)](https://code.google.com/p/webiopi/)
  - [web에서 gpio제어(webiopi) - youtube](https://www.youtube.com/watch?v=6RaBz01pi4E)

**Comment by lightreal** [comment]
#### 건전지 방전!!!
- 라즈베리파이와 모터테스트가 끝나면 건전지를 빼주세요. 그렇지 않으면 방전되어 건전지가 정상동작하지 않습니다.

**Comment by KimGunSoo** [comment]
기본적인 제어는 가능하므로 이 이슈는 닫습니다.
모터의 세부제어는 새로운 이슈(#18 )에서 다룹니다.
