### ISSUE TITLE
자료 정리 환경 구축

### ISSUE THREAD

**Issue by KimGunSoo** [KimGunSoo/sosohaniot#2]
# 자료정리 환경구축 확정안

일정 관리용 : git hub issues
자료 저장용 : git hub issues
프리젠테이션 자료 저장용 : google drive / presentation (나스카 문제 우회)

**Comment by lightreal** [comment]
github도 push가 오기 때문에 github로 하는게 좋을것 같음

**Comment by KimGunSoo** [comment]
### prezi 검토

프리젠테이션 자료 저장 목적으로 prezi를 검토해 보았다. (kjunu 제안, lightreal 검토)
한글을 입력할때 버그가 있고 도식화하기에 어려움이 있어, prezi는 보류하기로 결정함.
- kjunu의 제안
  - http://prezi.com/
  - 도식화하거나 이런덴 별 쓸모없었지만, 정말 발표를 위한 PT 자료툴이 필요할 때 쓸만하던데요 ㅎㅎㅎ
- lightreal의 검토
  - prezi는 큰 그림부터 세세한 부분으로 쪼개서 top - down 방식이나 순차적인 단계를 설명하기에 편함.
  - 그러나 한글입력에 약간 버그가 있는듯(in chrome).
  - 프레지 폴더에 Viewer 추가가 가능하나 뷰어가 업로드도 가능한지는 모르겠음.

**Comment by KimGunSoo** [comment]
### google drive / google presentation 검토

프리젠테이션 자료저장 툴로 google drive에 있는 google presentation을 검토해 보았다.
테마의 문제만 제외하면 도식화 하는데도 별 문제가 없어 google presentation으로 결정하였다.
- 테마
  - 기본 테마가 너무 부실하다는 단점이 있다.
  - ppt파일로 부터 다른 테마 가져오기를 할 수 있다. 하지만 글꼴이 없어서인지 글꼴관련 테마는 가져오지 못했다.
- 도식화
  -  power point 정도의 수준은 아니지만, 기본적인 도형을 그릴수 있다.
