### ISSUE TITLE
라즈베리파이 기초 이해 및 정리

### ISSUE THREAD

**Issue by KimGunSoo** [KimGunSoo/sosohaniot#3]
- 개요
  - 라즈베리파이의 기초들을 이해하고 정리하자.
- reference :
  - [엔하위키:라즈베리파이](https://mirror.enha.kr/wiki/%EB%9D%BC%EC%A6%88%EB%B2%A0%EB%A6%AC%20%ED%8C%8C%EC%9D%B4)
  - [강좌 링크모음](http://fishpoint.tistory.com/1377)

**Comment by kjunu** [comment]
https://www.youtube.com/watch?v=NhalgdxuOpU 1:30 정도까지 라즈베리파이 소개 (자막켜고 보면 괜춘하더라구요...)

https://www.youtube.com/watch?v=Z9jeZo0RHOc 이건 안드로이드 올리기

**Comment by kjunu** [comment]
2는 모르겠는데 1은 기본적으로 하드디스크 역할을 하는 게 sd 카드에요. 그런데 보통 이건 따로 사야합니다.

**Comment by kjunu** [comment]
라즈베리파이에 os 올리는 법은 sd 카드에 이미지를 구워서 라즈베리파이에 꽂으면 끝이에요.

sd 카드를 여러 개 가지고 여러 os 를 깔아두고 뺐다꼈다하면서 쓸 수도 있어요.

**Comment by kjunu** [comment]
sd 카드에 이미지 굽는 법은 리눅스는 dd 로 했던거 같고, 윈도우는 검색하면 그런 이미지 구워주는 프로그램(Win32DiskImager)이 나와요. 원하는 os 찾아서 구우면 됩니다.

**Comment by KimGunSoo** [comment]
### 라즈베리파이2 스펙 정리

라즈베리파이2 HW 스펙을 간단히 정리합니다.
항목들은 더 많았지만 필요한거 위주로 정리했습니다.
- Spec
  - CPU : ARM Cortex-A7 (Quad-core) 900MHz
  - Memory : 1GB LPDDR2
  - OS : Bootfs from Micro SD card, running a version of the Linux operating system
  - Power : Micro USB socket 5V, 2A
- Connector
  - ethernet : 10/100 BaseT Ethernet socket
  - USB : 4 x USB 2.0
  - GPIO : 40 pin 2.54mm(100mll) expansion header: 2x20 strip. Providing 27 GPIO pins as well as +3.3 V, +5 V and GND supply lines
  - Camera : 15 pin MIPI Camera Serial Interface (CSI-2)
  - Memory Card Slot : Micro SDIO

**Comment by KimGunSoo** [comment]
### 저장 장치

**SD 카드**를 저장장치로 사용하고 있습니다.
보드를 살때 포함되어있지 않으므로 따로 구매해야합니다.

라즈베리파이 설계상 SD 카드에서 OS를 로드하도록 되어있습니다.
따라서 SD 카드가 없으면 시작도 못합니다.
- 용량
  - 공식적으로 4GB 이상을 추천합니다.
  - 저희는 혹시 모르니 16GB로 준비했습니다.
- 타입
  - 라즈베리파이 B+ 이후 버젼부터는 기본적으로 **micro SD**를 장착하도록 되어있습니다.
  - 저희도 micro SD MLC 타입을 준비했습니다.

**Comment by KimGunSoo** [comment]
### 전원

micro USB socket을 통해 전원을 공급받습니다.
보통 **1A 스마트폰 충전기**를 사용하면 됩니다.
- 일반 USB 통해 전원 공급
  - USB 3.0 = 150mA ~ 900mA
  - USB 2.0 = 150mA ~ 500mA (전력 소모량이 더 커서 힘들다고 함)
  - 라즈베리파리 B+의 경우 기본적으로 600mA가 필요합니다.
  - 전력을 많이 소모하는 장치를 달 경우에는 유전원 허브가 필수적으로 필요합니다.

**Comment by KimGunSoo** [comment]
보드 스펙이나 구성에 대해서 알아보았습니다.
구체적인 내용들의 정리는 다른 이슈페이지를 만들어 작성하도록 합니다.

마지막으로, [강좌 모음 페이지](http://fishpoint.tistory.com/1377) **강추**입니다.
꼭 보세요.

**Comment by lightreal** [comment]
- 강좌모음페이지 데이터 장난 없네요.
- 중간중간에 카페링크가 있는데 글 읽으려면 오로카 카페정도 가입을 해 두는게 좋을 듯.
- pipc 카페는 가입없이도 볼 수 있습니다.
