### ISSUE TITLE
Road map 을 정하자.

### ISSUE THREAD

**Issue by kjunu** [KimGunSoo/sosohaniot#4]
최종 목표 : 드론 제작

드론 제작에 필요한 것들을 떠오르는 데로 정리한다.

그 중 일부만을 가지고 할 수 있는 것을 찾아서 새로운 이슈(중간 목표)를 만든다.

https://github.com/KimGunSoo/sosohaniot/wiki/Road-Map

**Comment by kjunu** [comment]
우선 모터가 필요합니다. 4개 이상의 모터를 달아서 라즈베리파이에 연결하여 on/off 할 수 있어야 합니다.

**Comment by kjunu** [comment]
댓글이 작성 후에 순서를 마음대로 조정할 수 없는 것 같아서 위키에 적었습니다.

**Comment by KimGunSoo** [comment]
준우가 1차적으로 Road map을 wiki에 정리하였습니다.
(https://github.com/KimGunSoo/sosohaniot/wiki/Road-Map)

해당 내용을 검토해 보았고, 약간의 정리와 약간의 stage를 더 넣었습니다.
모두 wiki의 Road map 페이지를 검토해 주시길 바랍니다.

1차적인 검토가 완료되면, 이 이슈는 close 할 것입니다. 

이 이슈가 close 되더라도 wiki의 Road map 페이지는 상황에 따라 바뀔 수 있습니다.

**Comment by kjunu** [comment]
https://www.youtube.com/watch?v=tc7AZWaHm4o

드론으로 이런 거 만들어도 좋을 것 같고.. 이미 있었던거 같긴한데... 걍 뭐 .. 모터 하나로 뭐 있지 생각하다 생각한 난 거 적어둠다.

**Comment by kjunu** [comment]
https://www.youtube.com/watch?v=iErFlwIdk0I (AA건전지를 동력으로 씀)

https://www.youtube.com/watch?v=a9dF4WGi0zg 

참고할 만 한 동영상

요약 : RC 카 + camera 가능함 ㅋ

https://www.youtube.com/watch?v=E-lXtJrgLvQ (2:00 부터)
보신 적 있을 텐데... 이게 완성형 일 듯

**Comment by lightreal** [comment]
film yourself 쩐당 ㅋㅋㅋ 아이디어가 좋네

**Comment by KimGunSoo** [comment]
완전 굿

**Comment by KimGunSoo** [comment]
추가적인 아이디어든 wiki에 정리하도록 하고 이 이슈는 닫습니다.
