### ISSUE TITLE
라즈베리파이에 올릴 OS 를 결정한다.

### ISSUE THREAD

**Issue by kjunu** [KimGunSoo/sosohaniot#5]
linux 계열 올리면 되겠죠?

**Comment by lightreal** [comment]
라즈베리안 OS 설치방법
http://voguebloom.blog.me/220037774604
http://blog.naver.com/elepartsblog/220179879204

**Comment by lightreal** [comment]
라즈베리용 Ubuntu Image Download
http://linux.softpedia.com/get/Linux-Distributions/RaspEX-103737.shtml

**Comment by KimGunSoo** [comment]
### 운영체제 검토

개발사인 라즈베리 재단에서는 **라즈베리안**을 추천하고 있다.
그외에 호환성이 확보 되는 다른 OS들도 홈페이지에 올려져 있다.
- 안드로이드
  - 2.3.3 진저브레드 까지는 올라갔으나, GPU EGL 드라이버가 칩셋 밴더에서 제공되지 않아 소프트웨어 모드로 구동되어 성능이 좋지 않음.
  - 브로드컴에서 4.0 ICS를 포팅하여 시연 영상을 올렸으나, 정작 공개는 안했음. GPU EGL 드라이버를 이론적으로는 포팅이 가능하다고 함.
- 우분투
  - ARM 지원 버젼은 있으나, 라즈베리파이의 CPU보다 높은 버젼만 지원하기 때문에 **설치가 불가능함**
  - 라즈베리파이2가 나오면서 우분투도 공식 지원 대상에 포함되게 됨
- Windows
  - Windows 쪽에서 라즈베리파이 장치를 지원해주지 않으면, 호환성 문제로 **설치가 불가능함**
  - 리눅스 위에 가상머신으로 Windows를 돌리는것은 가능함
- Raspbmc
  - TV에 연결해서 동영상을 재생하고 간단한 홈서버를 운영하는데 제격.
  - 최근 개발진이 업데이트를 중단하고, Kodi 기반의 OSMC(Open Source Media Center)를 개발하면서 OSMC 쪽이 활성화 되고있는 추세.

reference : [엔하위키:라즈베리파이](https://mirror.enha.kr/wiki/%EB%9D%BC%EC%A6%88%EB%B2%A0%EB%A6%AC%20%ED%8C%8C%EC%9D%B4)

**Comment by kjunu** [comment]
ubuntu 설치가 불가능 하다는건 x-server 띄우기가 버거워서 그런거라, 걍 설치할 수 있긴 해요. 쓰기가 좀 버벅거림 ㅋ

**Comment by kjunu** [comment]
제 추천은 arch linux 입니다.
http://archlinuxarm.org/platforms/armv6/raspberry-pi
http://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2

지원하는 package 들 많고 apt-get 대신에 pacman 이거 쓰면 별 차이 없이 쓴 거 같고
걍 깔고 공유기에 랜선으로 연결하면 알아서 NAT 잡아줌.
PC 에도 설치가능하니 개발 환경 꾸미기 편할 것 같아요. 

괜히 안드로이드 같은거 하면 크로스컴파일 환경 만들고 하는거 좀 귀찮다고 생각해서 ㅎ

**Comment by lightreal** [comment]
내 생각엔 라즈베리안으로 우선 시작을 해보고(라즈베리파이니까??ㅋㅋ)
확실히 딸리는구만... 이라고 생각될 때 바꿔도 되지 않을까?

**Comment by kjunu** [comment]
라즈베리안은 설치해서 사용하긴 좋은데 ... 개발하는 환경은 어떤거 생각하세요? ubuntu?

**Comment by KimGunSoo** [comment]
Ubuntu 공식 홈에서 CPU minimun System requirements 보니까, Desktop이 700MHz 이상, Server(CLI)가 300MHz이상 정도네.

라즈베리파이가 700MHz고 라즈베리파이2가 900MHz이니까 GUI를 이용하지 않는다면 Ubuntu도 괜찮을듯 하네.

reference : [Ubuntu systemd requirements](https://help.ubuntu.com/community/Installation/SystemRequirements)

**Comment by KimGunSoo** [comment]
### Raspbian vs. Arch Linux

이 둘 중 하나를 고르는게 어때?
- 고려사항
  - 우리에게 더 친숙한것.
  - 모터나 다른 디바이스에 대한 벤더 드라이버의 지원이 잘 되는것.
  - cross 컴파일 환경 구축이 쉬운것.

**Comment by kjunu** [comment]
둘 다 우리에게 생소
드라이버 지원은 커널 드라이버면 똑같다고 봐야하고...
cross 환경 잡는 것도 비슷한 난이도 일 것으로 예상합니도ㅏ
그냥 인지도 높은 라즈비안 가는 것도 좋겠네요. apt-get 되나봐요. ㅋㅋㅋ 

https://www.raspberrypi.org/documentation/raspbian/updating.md
https://www.raspberrypi.org/documentation/linux/software/apt.md

**Comment by kjunu** [comment]
고려사항 중에 그런 건 필요없을 까요? 물론 우리가 지금 프로젝트에서 라즈베리파이를 벗어날 일은 드물겠지만, 라즈비안은 어쨌든 다른 곳에 올려서 쓰기에는 어색함이 있는 것 같고 우분투나 기타 등등은 좀 더 범용적이라는 것?

**Comment by kjunu** [comment]
어찌되었든 개인적으로 한 30분 둘러본 의견은 라즈비안 한 표입니다. ㅎㅎㅎ

**Comment by KimGunSoo** [comment]
라즈베리안으로 최종 결정됨
