### ISSUE TITLE
cross 빌드 환경 구축

### ISSUE THREAD

**Issue by KimGunSoo** [KimGunSoo/sosohaniot#7]
- 개요
  - 코드를 컴파일해서 바이너리를 라즈베리파이에 옮겨서 실행해볼 수 있는 PC 환경을 구축한다.
- 환경 공유 방안
  1. 각자 따로 구축한다.
  2. vm 이미지를 만들어 배포한다.
  3. git hub에 script + bin 형식으로 올린다.
- reference
  - http://www.rasplay.org/?p=8567
  - http://openframeworks.cc/setup/raspberrypi/Raspberry-Pi-Cross-compiling-guide.html
  - http://lky1001.tistory.com/68

**Comment by kjunu** [comment]
라즈비안 cross compile 환경 구축하기
http://openframeworks.cc/setup/raspberrypi/Raspberry-Pi-Cross-compiling-guide.html

**Comment by lightreal** [comment]
갑자기 생각난건데... 크로스빌드가 필요한가??
라즈베리파이상에서 바로 빌드 가능하지 않을까?

**Comment by KimGunSoo** [comment]
라즈베리파이 안에서 빌드하려고 하면, 할수 있을꺼 같긴한데...
문제가 될만한 것들은..
- 컴파일 환경이 잘 되어있을까?
  - 컴파일러가 있을까? 헤더 파일이 있을까?
- 소스를 라즈베리파이로 카피해서 빌드해야한다는 단점이...
- 컴파일 환경이 통일되지 않을수도 있는 문제가...

**Comment by lightreal** [comment]
- 라즈베리파이에 apt-get으로 이것저것 설치가 가능함
  - 왠만한 컴파일환경은 쉽게 꾸밀 수 있을것 같아보임.(물론 직접해봐야 알겠지만... ㅎ)
- 소스를 카피해서 빌드해야 하는 단점
  - ui개발환경이 아니라면 라즈베리파이상에서 코딩할 수 있지 않을까?(불편하겠지만.. git도 될 것 같고)
- 라즈베리파이 상에서 개발 및 빌드하게 되면 크로스컴파일이 아닌거지? ㅋ
- 결론은... 우선 해봐야 알 것 같아 ㅋㅋㅋ sd카드가 빨리와야.. ㅎㅎ

**Comment by kjunu** [comment]
라즈베리파이 안에서 빌드 가능해요. 안에 git 설치해서 걍 거기서 클론 받아서 사용할 수도 있어요.
다만 클럭 속도가 낮으니 빌드가 오래걸리고, 커널레이어 같은 곳 작업할 일 있다면, 버그 한 방에 작업환경 다 날릴 수도 있다는 정도?

**Comment by KimGunSoo** [comment]
gcc만 간신히 구동되는 1차 버젼을 git에 올려 두었음.

아직 아무것도 안되겠지만, 사용법은 README를 읽어보면 되고,
해당 script들을 같이 변경 및 개발합시다.

**Comment by KimGunSoo** [comment]
라즈베리파이쪽 개발 언어를 python으로 선택하였기 때문에, 당장은 cross 빌드환경이 필요없게 되었다.
