### ISSUE TITLE
원격 접속환경 구축

### ISSUE THREAD

**Issue by KimGunSoo** [KimGunSoo/sosohaniot#8]
원격으로 라즈베리파이를 조정할 수 있는 환경을 구축한다.
- 라즈베리파이에 직접 모니터와 키보드를 연결하여 사용할 것이 아니기 때문에, ssh 같은 것을 통해 라즈베리파이에 접속할 수 있는 환경을 만들어야 한다.

> 기왕이면 라즈베리파이는 집에 다 두고 늘 켜두는 것도 괜찮을 것 같아요. 유동 IP 를 쓴다고 해도 한 번 받아둔 IP 가 변하지 않아서 일반적으로는 아무대서나 접속할 수 있으니...

**Comment by lightreal** [comment]
- ssh 환경꾸미기
- http://cafe.naver.com/openrt/2944
- NAT로 할지, 무선랜을 추가로 설치할지는 정해야 할 듯

**Comment by kjunu** [comment]
우선 유선랜 꽂아서 NAT 설정해보는 게 우선 일 것 같아요.
