### ISSUE TITLE
micro SDcard 구입

### ISSUE THREAD

**Issue by lightreal** [KimGunSoo/sosohaniot#9]
- 라즈비안 OS를 올리려면 micro SDcard 가 필요함
- 그냥 SDcard슬롯은 사라진 듯.
- 필요하신분 있으시면 같이 사면 좋을 듯

**Comment by lightreal** [comment]
- 부팅이 잘 되는지 확인하려면 hdmi-dvi or hdmi-hdmi cable 도 사야할 듯.
- ssh 접속하기 전에 ip setting 하기 위해서라도 필요함

**Comment by kjunu** [comment]
hdmi 랑 sd 저도 형들이랑 똑같은 걸로 사주세요. 어뎁터는 있으니 형태는 뭐가 되었든 상관 없어요 ㅎㅎㅎ 비용은 카톡으로 보내드릴깨요ㅋㅋㅋ

근데 hdmi 는 별로 필요없을 수도 있는게 ip setting 자동으로 될꺼에요. 집에 공유기에 할당된 ip 뭔지보고 들어가면 없어도 되긴 되는데... 없으니까 확실히 불편해서 이번에 형들 살 때 배송비도 아낄 겸 같이 신청합니다!

**Comment by KimGunSoo** [comment]
##### 주문 완료
- hdmi to hdmi 케이블 x 3
- hdmi to dvi 젠더 x 3
- micro SD 16GB x 3
- micro SD to SD 젠더 x 1
